package com.rosenstefanov.networthcalculator.core.ui.theme

import androidx.compose.ui.graphics.Color

// Brand identity: a blend of blue and purple (indigo / violet).

// Light scheme
val md_primary_light = Color(0xFF4F4CD8)
val md_onPrimary_light = Color(0xFFFFFFFF)
val md_primaryContainer_light = Color(0xFFE3DFFF)
val md_onPrimaryContainer_light = Color(0xFF0B0664)
val md_secondary_light = Color(0xFF5C5D9E)
val md_onSecondary_light = Color(0xFFFFFFFF)
val md_secondaryContainer_light = Color(0xFFE2DFFF)
val md_onSecondaryContainer_light = Color(0xFF181A56)
val md_tertiary_light = Color(0xFF7D4E9E)
val md_onTertiary_light = Color(0xFFFFFFFF)
val md_tertiaryContainer_light = Color(0xFFF2DAFF)
val md_onTertiaryContainer_light = Color(0xFF310953)
val md_error_light = Color(0xFFBA1A1A)
val md_onError_light = Color(0xFFFFFFFF)
val md_errorContainer_light = Color(0xFFFFDAD6)
val md_onErrorContainer_light = Color(0xFF410002)
val md_background_light = Color(0xFFFFFBFF)
val md_onBackground_light = Color(0xFF1B1B21)
val md_surface_light = Color(0xFFFFFBFF)
val md_onSurface_light = Color(0xFF1B1B21)
val md_surfaceVariant_light = Color(0xFFE4E1EC)
val md_onSurfaceVariant_light = Color(0xFF47464F)
val md_outline_light = Color(0xFF787680)

// Dark scheme
val md_primary_dark = Color(0xFFC4C0FF)
val md_onPrimary_dark = Color(0xFF1A1378)
val md_primaryContainer_dark = Color(0xFF332EA6)
val md_onPrimaryContainer_dark = Color(0xFFE3DFFF)
val md_secondary_dark = Color(0xFFC5C4DD)
val md_onSecondary_dark = Color(0xFF2D2F42)
val md_secondaryContainer_dark = Color(0xFF434559)
val md_onSecondaryContainer_dark = Color(0xFFE2DFFF)
val md_tertiary_dark = Color(0xFFE5B4FF)
val md_onTertiary_dark = Color(0xFF49196B)
val md_tertiaryContainer_dark = Color(0xFF633383)
val md_onTertiaryContainer_dark = Color(0xFFF2DAFF)
val md_error_dark = Color(0xFFFFB4AB)
val md_onError_dark = Color(0xFF690005)
val md_errorContainer_dark = Color(0xFF93000A)
val md_onErrorContainer_dark = Color(0xFFFFDAD6)
val md_background_dark = Color(0xFF1B1B21)
val md_onBackground_dark = Color(0xFFE4E1E9)
val md_surface_dark = Color(0xFF1B1B21)
val md_onSurface_dark = Color(0xFFE4E1E9)
val md_surfaceVariant_dark = Color(0xFF47464F)
val md_onSurfaceVariant_dark = Color(0xFFC8C5D0)
val md_outline_dark = Color(0xFF918F9A)
